version: "3.3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - mean-data:/app
    networks:
     - my-network
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mean-data:/data/db
    networks:
     - my-network
# define volume to be created
volumes:
  mean-data:
# define network to be created
networks:
  my-network:
